:green_heart: fix CI travis build
Don't know why the following happened:
---
Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18>
FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Name or service not known)
The command "elm package install --yes" failed and exited with 1 during .
---